<section class="static">
<h2>Die Regeln</h2>

<p>Wenn Du Dich hier für das Tippspiel interessierst, sind Dir mit
    hoher Wahrscheinlichkeit "traditionelle" Tipprunden und ihre Regeln bekannt.
    Im allgemeinen gibt es dort Punkte nach folgendem System:
    <ul>
        <li> 3 Punkte, wenn man das Ergebnis korrekt vorhergesagt hat, oder</li>
        <li> 2 Punkte, wenn man das Torverhältnis richtig getippt hat, oder</li>
        <li> 1 Punkte, wenn man wenigstens die Tendez richtig getippt hat.</li>
    </ul>
    Hat man nicht einmal die Tendenz richtig erkannt, geht man allerdings komplett leer aus.
    Das bringt unschöne Punktverteilungen mit sich, wie z.B.
    <ul>
        <li> Angenommen ein Spiel geht 1:1 aus,</li>
        <li> Spieler A tippte 1:2 und bekommt entsprechend 0 Punkte</li>
        <li> Spieler B tippte 7:7 und bekommt 2 Punkte.</li>
    </ul>
    Nun ist die Frage, wer näher am wahren Ergbnis war. Spieler B, mit 12 Toren Unterschied oder Spieler A,
    der sich nur um ein Tor geirrt hat.
</p>
    <p>Hier liegt die Motivation, für ein neues/anderes Regelwerk. Eines, das Tipps mehr belohnt, die dem
    Ergebnis näher liegen. Natürlich soll auch die Tordifferenz bei nicht zu hohen Abweichungen auch belohnt werden.
        Kommen wir also zu den Regeln: Das Prinzip ist, dass es bestimmte
        Grundpunkte gibt und bei Abweichungen vom Ergebnis werden Punkte davon abgezogen.</p>
    <ul>
        <li>Jeder bekommt für seinen Tipp 8 Punkte.</li>
        <li>Für jedes Tor Abweichung gibt es einen Punkt abzug.</li>
        <li>Für jedes Tor Abweichung bei der Tordifferenz, gibt es ein Punkt Abzug.</li>
        <li>Bei falscher Tendenz, gibt es pauschal 2 Punkte Abzug.</li>
        <li>Weniger als 0 Punkte für einen Tipp kann ein Spieler nicht machen.</li>
    </ul>

</section>