<section class="static">
<h2>Die Regeln</h2>

<p>Wenn Du Dich hier für das Tippspiel interessierst, sind Dir mit
    hoher Wahrscheinlichkeit "traditionelle" Tipprunden und ihre Regeln bekannt.
    Im allgemeinen gibt es dort Punkte nach folgendem System:
    <ul>
        <li> 3 Punkte, wenn man das Ergebnis korrekt vorhergesagt hat, oder</li>
        <li> 2 Punkte, wenn man das Torverhältnis richtig getippt hat, oder</li>
        <li> 1 Punkte, wenn man wenigstens die Tendez richtig getippt hat.</li>
    </ul>
    Hat man nicht einmal die Tendenz richtig erkannt, geht man allerdings komplett leer aus.
</p>

</section>