<section class="deliver">
    <h2>Abgabe</h2>
    <table class="table">
        <tr>
            <th>Spielbeginn</th>
            <th>Heimmannschaft</th>
            <th>Gastmannschaft</th>
        </tr>
        <?php foreach ($matches as $m) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($m->start);?></td>
                <td><?php echo $this->escapeHtml($m->team1name);?></td>
                <td><?php echo $this->escapeHtml($m->team2name);?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <hr />
<section>