<section class="deliver">
    <h2>Abgabe</h2>
    <?php if ($this->error): ?>
        <div class="error">
            Ein Fehler ist bei Deinem Abgabe-Versuch aufgetreten. Bitte versuche es noch einmal.
        </div>
    <?php endif ?>
    <?php if ($this->savedtips):
        if ($this->savedtips>0): ?>
        <div class="alert-success">
            Es
            <?php if ($this->savedtips==1):
                echo " wurde ein Tipp ";
            else:
                echo " wurden ".$this->savedtips. " Tipps ";
            endif  ?>
            gespeichert.
        </div>
        <?php endif ?>
    <?php endif ?>

    <?php
    $form1 = $this->form;
    $form1->prepare();
    $form1->setAttribute('action', $this->url(NULL,array('controller'=>'deliver', 'action'=>'index')));
    $form1->setAttribute('method', 'post');
    echo $this->form()->openTag($form1);
    echo $this->formElement($form1->get('select'));
    echo $this->form()->closeTag($form1);
    ?>

    <?php
    $form2 = $this->form;
    $form2->prepare();
    $form2->setAttribute('action', $this->url(NULL,array('controller'=>'deliver', 'action'=>'index')));
    $form2->setAttribute('method', 'post');
    echo $this->form()->openTag($form2);
    echo $this->formElement($form2->get('day'));
    ?>
    <table class="table">
        <tr>
            <th>Spielbeginn</th>
            <th>Heimmannschaft</th>
            <th>Gastmannschaft</th>
            <th>Tipp</th>
        </tr>
        <?php $i=0; foreach ($matches as $m) :
            $i++;
            #Zend:Debug::Dump('a  '.'match'.$i.'_team1');
            ?>
            <tr>
                <td><?php echo $this->escapeHtml($m->start);?></td>
                <td>
                    <img src="<?php echo $this->basePath().'/img/emblem/'.$m->team1emblem;?>"/>
                    <?php echo $this->escapeHtml($m->team1name);?>
                </td>
                <td>
                    <img src="<?php echo $this->basePath().'/img/emblem/'.$m->team2emblem;?>"/>
                    <?php echo $this->escapeHtml($m->team2name);?>
                </td>
                <td><?php
                        echo $this->formElement($form2->get('match'.$i.'_team1'));
                        echo ' : ';
                        echo $this->formElement($form2->get('match'.$i.'_team2'));
                    ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->formElement($form2->get('submit')); ?>
    <?php echo $this->form()->openTag($form2); ?>

    <hr />
<section>