<section class="login">
    <h2>Login</h2>
    <?php if ($this->error): ?>
        <p class="error">
            Ein Fehler ist bei Deinem Login-Versuch aufgetreten. Bitte versuche es noch einmal.
        </p>
    <?php endif ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL,array('controller'=>'Login', 'action'=>'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>

    <d1 class="zend_form">
        <dt><?php echo $this->formLabel($form->get('name'));?></dt>
        <dd>
            <?php
            echo $this->formElement($form->get('name'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('password'));?></dt>
        <dd>
            <?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
        </dd>
        </d1></br>
        <dd>
            <?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>
        </dd>
    </d1>
    </br><p>Noch kein Account? <a href="/users/register">Registriere Dich jetzt hier.</a></p>
    <?php echo $this->form()->closeTag(); ?>
</section>