<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Grisujis '. $this->translate('Tippspiel'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('application/rank') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Grisujis Tippspiel"/>&nbsp;<?php echo $this->translate('Grisuji`s Tippspiel') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li ><a href="<?php echo $this->url('application/rank') ?>"><?php echo $this->translate('Tabelle') ?></a></li>
                        <li ><a href="<?php echo $this->url('application/waswenn') ?>"><?php echo $this->translate('Was wäre wenn?') ?></a></li>
                        <li ><a href="<?php echo $this->url('application/userpoints') ?>"><?php echo $this->translate('Einzelpunkte') ?></a></li>
                        <?php if ($user = $this->identity() and $user->name == "admin") { ?>
                            <li ><a href="<?php echo $this->url('users/user-manager') ?>"><?php echo $this->translate('Manage Users') ?></a></li>
                        <?php } ?>
                        <?php if ($user = $this->identity()) { ?>
                            <li ><a href="<?php echo $this->url('application/deliver') ?>"><?php echo $this->translate('Tippen') ?></a></li>
                            <li ><a href="<?php echo $this->url('users/user-manager', array('action' => 'edit')) ?>"><?php echo $this->translate('Profil') ?></a></li>
                            <li ><a href="<?php echo $this->url('users/login', array('action' => 'logout')) ?>"><?php echo $this->translate('Logout') ?></a></li>
                        <?php } else { ?>
                            <li ><a href="<?php echo $this->url('users/login') ?>"><?php echo $this->translate('Login') ?></a></li>
                        <?php } ?>
                        <li ><a href="<?php echo $this->url('application/static', array('action' => 'rules')) ?>"><?php echo $this->translate('Regeln') ?></a></li>
                        <li ><a href="<?php echo $this->url('application/static', array('action' => 'impressum')) ?>"><?php echo $this->translate('Impressum') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by Grisuji. <?php echo $this->translate(' All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
