<section class="register">
    <h2>Registrierung</h2>
    <?php if ($this->error and $this->type == "default"): ?>
        <p class="error">
            Es sind ein oder mehrere Fehler bei der Registrierung aufgretreten. Bitte behebe sie bei den markierten Feldern und versuche es noch einmal.
        </p>
    <?php elseif ($this->error and $this->type == "username"):?>
        <p class="error">
            Der gewählte Username ist schon vergeben. Bitte wähle einen anderen.
        </p>
    <?php endif ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL,array('controller'=>'Register', 'action'=>'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>

    <d1 class="zend_form">
        <dt><?php echo $this->formLabel($form->get('name'));?></dt>
        <dd>
            <?php
            echo $this->formElement($form->get('name'));
            echo $this->formElementErrors($form->get('name'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('email'));?></dt>
        <dd>
            <?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('password'));?></dt>
        <dd>
            <?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('confirm_password'));?></dt>
        <dd>
            <?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password'));
            ?>
        </dd></br>
        <dd>
            <?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>
        </dd>
    </d1>
    <?php echo $this->form()->closeTag(); ?>
</section>