CREATE DATABASE IF NOT EXISTS tippspiel_db;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL ,
  email VARCHAR(255) NOT NULL ,
  password TEXT NOT NULL,
  avatar VARCHAR(255),
  motto VARCHAR(255),
  registerdate DATETIME,
  lastlogin DATETIME,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
);

INSERT INTO user (id, name, email, password) VALUES (1, 'admin', 'grisuji@gmx.de','21232f297a57a5a743894a0e4a801fc3');

CREATE TABLE IF NOT EXISTS tipp (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  userid INTEGER UNSIGNED NOT NULL,
  spielid INTEGER UNSIGNED NOT NULL,
  heimtore INTEGER UNSIGNED,
  gasttore INTEGER UNSIGNED,
  PRIMARY KEY (id),
  UNIQUE KEY (userid, spielid)
);

CREATE TABLE IF NOT EXISTS mannschaft (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  lang VARCHAR(255) NOT NULL,
  kurz VARCHAR(255) NOT NULL,
  wappen VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS spiel (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  liga INTEGER UNSIGNED NOT NULL,
  saison INTEGER UNSIGNED NOT NULL,
  spieltag INTEGER UNSIGNED NOT NULL,
  spielzeit DATETIME,
  heimid INTEGER UNSIGNED NOT NULL,
  gastid INTEGER UNSIGNED NOT NULL,
  heimtore INTEGER UNSIGNED,
  gasttore INTEGER UNSIGNED,
  isfinished BOOL DEFAULT FALSE,
  PRIMARY KEY (id)
);
