CREATE DATABASE IF NOT EXISTS tippspiel_db;
USE tippspiel_db;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL ,
  email VARCHAR(255) NOT NULL ,
  password TEXT NOT NULL,
  avatar VARCHAR(255),
  motto VARCHAR(255),
  registerdate DATETIME,
  lastlogin DATETIME,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
);

INSERT INTO user (id, name, email, password) VALUES (1, 'admin', 'grisuji@gmx.de','21232f297a57a5a743894a0e4a801fc3');

CREATE TABLE IF NOT EXISTS tips (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  userid INTEGER UNSIGNED NOT NULL,
  matchid INTEGER UNSIGNED NOT NULL,
  team1goals INTEGER UNSIGNED,
  team2goals INTEGER UNSIGNED,
  PRIMARY KEY (id),
  UNIQUE KEY (userid, matchid)
);

CREATE TABLE IF NOT EXISTS teams (
  id INTEGER UNSIGNED NOT NULL,
  longname VARCHAR(255) NOT NULL,
  shortname VARCHAR(255),
  emblem VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS matchs (
  id INTEGER UNSIGNED NOT NULL,
  league VARCHAR(255) NOT NULL,
  saison VARCHAR(255) NOT NULL,
  groupid INTEGER UNSIGNED NOT NULL,
  date_time DATETIME,
  team1id INTEGER UNSIGNED NOT NULL,
  team2id INTEGER UNSIGNED NOT NULL,
  team1goals INTEGER UNSIGNED,
  team2goals INTEGER UNSIGNED,
  isfinished BOOL DEFAULT FALSE,
  PRIMARY KEY (id)
);
