<section class="userpoints">
    <h2>Spielerpunkte</h2>

    <?php
    $form1 = $this->form;
    $form1->prepare();
    $form1->setAttribute('action', $this->url(NULL,array('controller'=>'userpoints', 'action'=>'process')));
    $form1->setAttribute('method', 'post');
    echo $this->form()->openTag($form1);
    echo $this->formElement($form1->get('selected_day'));
    echo $this->formElement($form1->get('hidden_userid'));
    echo $this->form()->closeTag($form1);
    ?>

    <?php
    $form2 = $this->form;
    $form2->prepare();
    $form2->setAttribute('action', $this->url(NULL,array('controller'=>'userpoints', 'action'=>'process')));
    $form2->setAttribute('method', 'post');
    echo $this->form()->openTag($form2);
    echo $this->formElement($form2->get('hidden_day'));
    echo $this->formElement($form2->get('selected_userid'));
    echo $this->form()->closeTag($form2);
    ?>

    <table class="table">
        <tr>
            <th>Spielbeginn</th>
            <th>Heimmannschaft</th>
            <th>Gastmannschaft</th>
            <th>Ergebnis</th>
            <th>Tipp</th>
            <th>Punkte</th>
        </tr>
        <?php $i=0; foreach ($matches as $m) :
            $i++;
            ?>
            <tr>
                <td><?php echo $this->escapeHtml($m->start);?></td>
                <td>
                    <img src="<?php echo $this->basePath().'/img/emblem/'.$m->team1emblem;?>"/>
                    <?php echo $this->escapeHtml($m->team1name);?>
                </td>
                <td>
                    <img src="<?php echo $this->basePath().'/img/emblem/'.$m->team2emblem;?>"/>
                    <?php echo $this->escapeHtml($m->team2name);?>
                </td>
                <td><?php
                    echo $this->escapeHtml($m->team1goals);
                    echo ' : ';
                    echo $this->escapeHtml($m->team2goals);
                    ?>
                </td>
                <td><?php
                    echo $this->escapeHtml($m->team1tip);
                    echo ' : ';
                    echo $this->escapeHtml($m->team2tip);
                    ?>
                </td>
                <td><?php
                    echo $this->escapeHtml($m->points);
                    ?>
                </td>

            </tr>
        <?php endforeach; ?>
    </table>
</section>