<section class="userpoints">
    <h1><?php echo $this->userinfo->name ?> </h1>
    <h4><?php echo $this->userinfo->motto ?> </h4>
    <table class="table">
        <tr>
            <td>
                Auswahl des Spielers:
            </td>
            <td>
                <?php
                $form2 = $this->form;
                $form2->prepare();
                $form2->setAttribute('action', $this->url(NULL,array('controller'=>'userpoints', 'action'=>'process')));
                $form2->setAttribute('method', 'post');
                echo $this->form()->openTag($form2);
                echo $this->formElement($form2->get('hidden_day'));
                echo $this->formElement($form2->get('selected_userid'));
                echo $this->form()->closeTag($form2);
                ?>
            </td>
            <td>
                Auswahl des Spieltags:
            </td>
            <td>
                <?php $form1 = $this->form;
                $form1->prepare();
                $form1->setAttribute('action', $this->url(NULL,array('controller'=>'userpoints', 'action'=>'process')));
                $form1->setAttribute('method', 'post');
                echo $this->form()->openTag($form1);
                echo $this->formElement($form1->get('selected_day'));
                echo $this->formElement($form1->get('hidden_userid'));
                echo $this->form()->closeTag($form1);
                ?>
            </td>
        </tr>
    </table>
        <table class="table">
        <tr>
            <th>Spielbeginn</th>
            <th>Heimmannschaft</th>
            <th>Gastmannschaft</th>
            <th>Ergebnis</th>
            <th>Tipp</th>
            <th>Punkte</th>
            <th style="color:#A4A4A4">Todde</th>
        </tr>
        <?php $i=0; foreach ($live as $m) :
            $i++;
            ?>
            <tr>
                <td><?php echo $this->escapeHtml($m->start);?></td>
                <td>
                    <img src="<?php echo $this->basePath().'/img/emblem/'.$m->team1emblem;?>"/>
                    <?php echo $this->escapeHtml($m->team1name);?>
                </td>
                <td>
                    <img src="<?php echo $this->basePath().'/img/emblem/'.$m->team2emblem;?>"/>
                    <?php echo $this->escapeHtml($m->team2name);?>
                </td>
                <td align="center"><?php
                    echo $this->escapeHtml($m->team1goals);
                    echo ' : ';
                    echo $this->escapeHtml($m->team2goals);
                    ?>
                </td>
                <td align="center"<?php
                    if ($m->istodddetip) {
                        echo ' style="color:#A4A4A4">';
                    } else {
                        echo '>';
                    }
                    echo $this->escapeHtml($m->team1tip);
                    echo ' : ';
                    echo $this->escapeHtml($m->team2tip);
                    ?>
                </td>
                <td><?php
                    if ($m->getPoints() > 0) echo $this->escapeHtml($m->getPoints());
                    ?>
                </td>
                <td style="color:#A4A4A4"><?php
                    if ($m->getToddde() > 0) echo $this->escapeHtml($m->getToddde());
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <div  id="container"  style="height: 400px;">
    </div>

</section>