<?php $this->headScript()
    ->appendFile($this->basePath().'/js/highcharts.js', 'text/javascript')
    ->appendScript('$(function () {$("#hc_container").highcharts(
        '.$this->diagram.'
    )});');
echo $this->headScript();
?>
<section class="ranking">
    <h2>Spieltag  <?php echo $this->day ?></h2>
    <table class="table" >
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <?php foreach ($this->live['matches'] as $matchid) { ?>
                <th <?php if($this->live[$matchid]['finished'] == 0): ?>
                    style="color:red"
                <?php endif ?>
                    >
                    <img src="<?php echo $this->basePath().'/img/emblem/'.$this->live[$matchid]['emblem1'];?>"/></br>
                    <?php if ($live[$matchid]['goals1']!="") {
                        echo $live[$matchid]['goals1'];
                        echo ":";
                        echo $live[$matchid]['goals2'];
                    }?>
                    </br>
                    <img src="<?php echo $this->basePath().'/img/emblem/'.$this->live[$matchid]['emblem2'];?>"/>

                </th>
            <?php } ?>
            <th style="color:#A4A4A4">Toddde</th>
        </tr>
        <?php
        $mem_rank = -1;
        foreach($this->user as $id => $u){
            ?>
            <tr>
                <td>
                    <?php if ($mem_rank!= $u['rank']) { echo $u['rank']; } ?>
                </td>
                <td>
                    <a href="<?php echo $this->url('application/userpoints', array('userid' => $u['id'], 'day' => $this->day)) ?>"><?php echo $this->escapeHtml($u['name']);?></a>
                </td>
                <td>
                    <?php echo $this->escapeHtml($u['points']); echo "/" ;echo $this->escapeHtml($u['points_all']);?>
                </td>
                <?php foreach ($this->live['matches'] as $matchid) { ?>
                    <td <?php if ($u['matches'][$matchid] == 0): ?>
                        style="color:#A4A4A4"
                    <?php endif ?>
                        >
                        <?php if (isset($u['matches'][$matchid]['tip1'])) {
                            echo $u['matches'][$matchid]['tip1'];
                            echo ":";
                            echo $u['matches'][$matchid]['tip2'];
                        } ?>
                        <?php if ($u['matches'][$matchid]['points'] > 0): ?>
                            <strong style="color:darkgreen;font-size:100%">
                                <sub>
                                    <?php echo $u['matches'][$matchid]['points']; ?>
                                </sub>
                            </strong>
                        <?php endif ?>
                    </td>
                <?php } ?>
                <td style="color:#A4A4A4">
                    <?php echo $this->escapeHtml($u['toddde']); echo "/" ; echo $this->escapeHtml($u['toddde_all']);?>
                </td>
            </tr>
            <?php
            $mem_rank = $u['rank'];
        } ?>
    </table>
    <div id="hc_container" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
</section>