<section class="ranking">
    <h2>Tabelle</h2>
    <table class="table">
        <tr>
            <th>Platz</th>
            <th>Spieler</th>
            <th>Spieltag <?php echo $this->day ?></th>
            <th>Gesamt</th>
            <th style="color:#A4A4A4">Todde</th>
        </tr>
        <?php $platz=0;
                $mem_points = -1;
                foreach($this->user as $id => $u){
                    if ($mem_points != $u['points']) {
                        $platz++;
                    }
                    $mem_points = $u['points'];
                    ?>
            <tr>
                <td>
                    <?php echo $platz; ?>
                </td>
                <td>
                    <a href="<?php echo $this->url('application/userpoints', array('userid' => $u['id'], 'day' => $this->day)) ?>"><?php echo $this->escapeHtml($u['name']);?></a>
                </td>
                <td>
                    <?php echo $this->escapeHtml($u[$this->day]);?>
                </td>
                <td>
                    <?php echo $this->escapeHtml($u['points']);?>
                </td>
                <td style="color:#A4A4A4">
                    <?php echo $this->escapeHtml($u['todde_day']); echo "/" ; echo $this->escapeHtml($u['todde']);?>
                </td>
            </tr>
        <?php } ?>
    </table>
</section>